name: flutter_highlighted_text
description: "Flutter widget to find, highlight, and enable taps on specific text patterns."
version: 0.0.1
repository: 'https://github.com/Miso-0/flutter_highlighted_text'

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:

topics:
  - highlight
  - text
  - regular-expression
  - search
  - tap

flutter: